### ISSUE TITLE
As an admin, I want to sort customers by Id, Name, Email so that I can quickly find and access specific customer information

### ISSUE THREAD

**Issue by JohnoAlm** [KYH-Net23/IdentityUserService#29]
**Made by Hossén & Oliver**

# Acceptance Criteria:

- [ ] The admin should be able to click a ‘Sort by’ button that triggers a dropdown menu.
- [ ] The dropdown menu should display sorting options for Id, Name and Email that can be clicked and trigger the sorting.
- [ ] After the sorting, the list of customers should be correctly updated and displayed based on the sorting criteria.

# Tasks:
- [ ] Implement UI/frontend.
  - [ ] Task 1: Create a "Sort by" button.
  - [ ] Task 2: Create a dropdown menu with Id, Name and Email as clickable options
  - [ ] Task 3: Display list of customers.
- [ ] Task 4: Create a customer/user list view model (Customer ID, Name, Email and Status?).
- [ ] Task 5: Implement a function for fetching customers from the database, sorting them and returning a new list.
- [ ] Task 6: Implement a function for mapping the sorted customer list to a list of the new customer/user list view model.
- [ ] Task 7: Implement a function that sends a request to an API and gets the updated list of customers as a  response.
- [ ] Task 8: Implement authorization.

# Test Cases:

- [ ] **Case 1:** Verify that the correct list of customers is updated according to the sorting criteria.
  - Prerequisites: User is logged in as an admin. Admin is navigated to the customer list page. There is at least one customer in the system.
- Steps:
  - Click on the ‘Sort by’ dropdown button.
  - Click on one of the sorting options displayed in the dropdown menu.
- Expected Results:
  - The system displays an up to date list showing results that are sorted according to the sorting criteria. 

# Activity Diagram
![Image](https://github.com/user-attachments/assets/2cb72702-4e5f-4392-8f01-bf49653f40ce)
