### ISSUE TITLE
As an admin I want to be able to reset my password from the login page if I have forgotten it.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/IdentityUserService#3]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [ ] There should be a form for entering the user’s email address.
- [ ] An email should be sent to the user, with a link to reset the password.
- [ ] There should be a form for entering the new password.
- [ ] After the new password has been created an email with a link containing reset instructions should be sent to the user’s email address.

# Tasks:
- [ ] KYH-Net23/Rika#115
- [ ] KYH-Net23/Rika#116
- [ ] KYH-Net23/Rika#117
- [ ] KYH-Net23/Rika#118
- [ ] KYH-Net23/Rika#119
- [ ] KYH-Net23/Rika#120
- [ ] KYH-Net23/AdminEmailService#1
- [ ] #11

# Test Cases:
### Expected Results:

# Activity Diagram: ![Image](https://github.com/user-attachments/assets/9edceec4-0fa5-42e9-adb7-880c870bb51c)
