### ISSUE TITLE
As an admin I want to be able to create a new customer account so that I can add users to our system.

### ISSUE THREAD

**Issue by IsabelHaataja** [KYH-Net23/IdentityUserService#31]
Authors: Kimmo Ahola & Isabel Haataja

## Acceptance Criteria:
- [ ] There needs to be a “create new customer account” button.
- [ ] There needs to be a “cancel” button.
- [ ] There needs to be a “create new customer account” form.
- [ ] There needs to be error validation on the form with an error message if something goes wrong.
- [ ] The new account should not be created if there are errors in the form.
- [ ] The new account should be saved to a database.
- [ ] Duplicate emails are not allowed.

## Tasks:
- [ ] KYH-Net23/Rika#96
- [ ] Implement a “Create” button to the form.
- [ ] Implement a "Cancel" button to the form.
- [ ] Implement form validation.
- [ ] KYH-Net23/AdminCustomerSettingService#33
- Name
- Email
- Birthdate
- Gender
- Password
- Date Created for account
- Account Status
- Last Login Date for account
- [ ] KYH-Net23/AdminCustomerSettingService#34
- [ ] KYH-Net23/AdminEmailService#2
- [ ] The confirmation email should include a link to the Login page. 
- [ ] KYH-Net23/AdminCustomerSettingService#36

## Activity Diagram: 
![Image](https://github.com/user-attachments/assets/889348d0-a369-4492-8c12-c5591dfb52da)

## Test Cases:

- [ ] **Case 1:**
Prerequisites: 
The user is logged in as an admin
The admin has navigated to the create customer page.
Steps: 
Press the “create new customer account” button.
Fill the form with valid property values.
Press “Create”
Expected Results: A success message appears.

- [ ] **Case 2:**
Prerequisites: Admin tries to duplicate an email.
Steps:
Enter an email that already exists in the email field.
Attempt to create a new account.
Expected Results: The system displays a message that the email is already taken.

- [ ] **Case 3:**
Prerequisites:
Steps:
Leave a/several fields blank
Attempt to create a new account.
Expected Results: The system prevents creation and displays an error message.

- [ ] **Case 4:**
Prerequisites: Admin tries to cancel while creating.
Steps:
Enter values to fields.
Press “Cancel”.
Expected Results: The system does not create a new customer account.

- [ ] **Case 5:**
Prerequisites: 
The user is logged in as an admin
The admin has navigated to the create customer page.
Steps: 
Press the “create new customer account” button.
Fill the form with valid property values.
Press “Create”
Expected Results: A new customer account has been created and saved to the database.

- [ ] **Case 6:**
Prerequisites: 
The user is logged in as an admin
The admin has navigated to the create customer page.
Steps: 
Press the “create new customer account” button.
Fill the form with valid property values.
Press “Create”
Expected Results: The customer gets an email confirmation.

- [ ] **Case 7:**
Prerequisites: 
The user is logged in as an admin
The admin has navigated to the create customer page.
Steps: 
Press the “create new customer account” button.
Fill the form with invalid property values.
Press “Create”
Expected Results: An error message is displayed and a new customer account is not created.

**Comment by KimmoKAhola** [comment]
not necessary to implement this
