### ISSUE TITLE
As an admin I want to be able to view an overview of an admin account’s history so I can quickly get information about all changes that an admin has made.

### ISSUE THREAD

**Issue by IsabelHaataja** [KYH-Net23/IdentityUserService#37]
Authors: Kimmo Ahola & Isabel Haataja

## Acceptance Criteria:

- [ ] Every change made to a user or to the system has to be saved to a database.
- [ ] There needs to be a “show more/details” button that makes it possible to add notes to the activity.
- [ ] Only relevant information should be visible.
- [ ] If there is no history at all, the page should display a special message.
- [ ] Only logged in admin accounts should see this overview page.
- [ ] The types of history actions are: Product management, stock management, order management, customer management, report generation.
- [ ] The history should be displayed in chronological order.

## Tasks: 
- [ ]  **Task 1:** Fetch history data from an external API.
- [ ] **Task 2:** Implement an API to call when saving the changes made.
- [ ] KYH-Net23/Rika#121
- [ ] Implement a “show more/details” button.
- [ ] Implement a “no history” message.
- [ ] **Task 4:** Implement a database for the account history.
- [ ] **Task 5:** Implement a change history data model
- Action type Enum (PRODUCT_CHANGE, ACCOUNT_CHANGE, order, stock, etc.)
- Date of change
- The admin User ID
- Content/Reason (nullable)

## Activity Diagram:
![Image](https://github.com/user-attachments/assets/13f129c2-9b2e-4ba5-89c9-b12e3584e941)

## Test Cases:
- [ ] **Case 1:**
Prerequisites: The user is logged in as an admin.
Steps:
Select an admin account and view its account history.
Verify that history data is fetched and displayed.
Expected Results: The system fetches and displays accurate historical data for the selected admin account.
